from app.schemas.domain import EvidenceType


SEED_EVIDENCE = [
    {"evidence_id": "ev_policy_lifeline", "type": EvidenceType.POLICY, "source_id": "seed-policy-001", "title": "城市基础设施生命线安全工程建设要求", "content": "推动城市生命线安全工程建设，建设监测感知、风险评估、预警处置和协同调度能力。", "organization": "住房城乡建设主管部门", "source_url": "https://example.invalid/policy/lifeline", "relevance": 0.94, "reliability": 1.0, "effective_date": "2024-01-01"},
    {"evidence_id": "ev_industry_lifeline", "type": EvidenceType.INDUSTRY, "source_id": "seed-industry-001", "title": "城市生命线建设业务说明", "content": "城市生命线通常覆盖燃气、供水、排水、桥梁和道路等场景，需要物联感知、数据治理、模型分析和事件处置闭环。", "organization": None, "source_url": None, "relevance": 0.9, "reliability": 0.85, "effective_date": None},
    {"evidence_id": "ev_org_housing", "type": EvidenceType.RESPONSIBILITY, "source_id": "seed-org-001", "title": "住房城乡建设局职责", "content": "住房城乡建设主管部门统筹城市基础设施建设管理，并组织推进城市运行安全相关工作。", "organization": "住房城乡建设局", "source_url": "https://example.invalid/org/housing", "relevance": 0.92, "reliability": 1.0, "effective_date": None, "metadata": {"record_type": "organization_card", "organization_id": "org_housing", "organization_name": "住房城乡建设局", "department_id": None}},
    {"evidence_id": "ev_dept_urban", "type": EvidenceType.RESPONSIBILITY, "source_id": "seed-dept-001", "title": "城市建设处职责", "content": "城市建设处负责城市市政基础设施建设、运行管理相关工作，牵头协调专项建设任务。", "organization": "住房城乡建设局", "source_url": "https://example.invalid/org/urban-construction", "relevance": 0.9, "reliability": 1.0, "effective_date": None, "metadata": {"record_type": "organization_card", "organization_id": "org_housing", "organization_name": "住房城乡建设局", "department_id": "dept_urban_construction", "department_name": "城市建设处"}},
    {"evidence_id": "ev_case_lifeline", "type": EvidenceType.CASE, "source_id": "seed-case-001", "title": "某市城市生命线安全工程案例", "content": "该项目由住建主管部门牵头，城市建设处协调，建设城市生命线监测预警平台。", "organization": "某市住房城乡建设局", "source_url": None, "relevance": 0.88, "reliability": 0.9, "effective_date": "2023-06-01", "metadata": {"record_type": "case_card", "case_id": "seed-case-001"}},
    {"evidence_id": "ev_capability_data", "type": EvidenceType.CAPABILITY, "source_id": "seed-capability-001", "title": "城市生命线数据治理能力", "content": "公司具备多源城市基础设施数据接入、数据治理、风险模型和可视化指挥能力。", "organization": "公司", "source_url": None, "relevance": 0.91, "reliability": 0.95, "effective_date": None, "metadata": {"record_type": "capability_card", "capability_id": "cap_lifeline_data", "case_ids": ["seed-case-001"]}},
    {"evidence_id": "ev_internal_lifeline_followup", "type": EvidenceType.INTERNAL, "source_id": "seed-expert-knowledge-001", "title": "已审核的城市生命线实施范围核验经验", "content": "已审核的内部经验提示：城市生命线项目进入下一轮商务沟通前，应先核验建设范围与协同边界。该经验只作补充参考，不能替代当前项目的原始证据。", "organization": None, "source_url": None, "relevance": 0.8, "reliability": 0.8, "effective_date": None, "metadata": {"record_type": "expert_knowledge", "knowledge_status": "PUBLISHED", "version": 1}}
]
